export const types = {
	APP_START: "APP_START",
	TOOL_GENERATE_RANDOM_MAP: 'TOOL_GENERATE_RANDOM_MAP', 
	EXPORT: 'EXPORT',
	EXPORT_COMPLETE: 'EXPORT_COMPLETE',
	RANDOM_MAP_START: 'RANDOM_MAP_START',
	RANDOM_MAP_COMPLETE: 'RANDOM_MAP_COMPLETE',
};